# The `test/support/gen/**` subtree holds throwaway proto oracle modules
# generated by `mix a2a.gen_proto` (git-ignored). protoc-gen-elixir's output
# is not formatted to this project's style, and it must never be reformatted or
# fail `mix format --check-formatted`. Elixir 1.14's formatter has no `:exclude`
# option, so expand the input globs and subtract the generated subtree.
[
  inputs:
    Enum.flat_map(
      ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
      &Path.wildcard(&1, match_dot: true)
    ) -- Path.wildcard("test/support/gen/**/*.{ex,exs}"),
  line_length: 100
]
