# The `test/support/gen/**` subtree holds throwaway proto oracle modules
# generated by `mix a2a.gen_proto` (git-ignored). protoc-gen-elixir's output
# is not formatted to this project's style, and it must never be reformatted or
# fail `mix format --check-formatted`, so exclude it via the formatter's
# `:excludes` option (available since Elixir 1.19).
[
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  excludes: ["test/support/gen/**/*.{ex,exs}"],
  line_length: 100
]
